// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using MLNetTableSoccerML.Model.GoalDifference;

namespace MLNetTableSoccerML.ConsoleApp.GoalDifference
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"D:\softaware\samples-ml\data\tablesoccer-export.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual GoalDifference with predicted GoalDifference from sample data...\n\n");
            Console.WriteLine($"Hour: {sampleData.Hour}");
            Console.WriteLine($"Weekday: {sampleData.Weekday}");
            Console.WriteLine($"Team1GoalKeeper: {sampleData.Team1GoalKeeper}");
            Console.WriteLine($"Team1Striker: {sampleData.Team1Striker}");
            Console.WriteLine($"Team2GoalKeeper: {sampleData.Team2GoalKeeper}");
            Console.WriteLine($"Team2Striker: {sampleData.Team2Striker}");
            Console.WriteLine($"GoalsTeam1: {sampleData.GoalsTeam1}");
            Console.WriteLine($"GoalsTeam2: {sampleData.GoalsTeam2}");
            Console.WriteLine($"Result: {sampleData.Result}");
            Console.WriteLine($"\n\nActual GoalDifference: {sampleData.GoalDifference} \nPredicted GoalDifference: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
