// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLNetTableSoccerML.Model.Winner
{
    public class ModelInput
    {
        [ColumnName("Hour"), LoadColumn(0)]
        public float Hour { get; set; }


        [ColumnName("Weekday"), LoadColumn(1)]
        public string Weekday { get; set; }


        [ColumnName("Team1GoalKeeper"), LoadColumn(2)]
        public string Team1GoalKeeper { get; set; }


        [ColumnName("Team1Striker"), LoadColumn(3)]
        public string Team1Striker { get; set; }


        [ColumnName("Team2GoalKeeper"), LoadColumn(4)]
        public string Team2GoalKeeper { get; set; }


        [ColumnName("Team2Striker"), LoadColumn(5)]
        public string Team2Striker { get; set; }


        [ColumnName("GoalsTeam1"), LoadColumn(6)]
        public float GoalsTeam1 { get; set; }


        [ColumnName("GoalsTeam2"), LoadColumn(7)]
        public float GoalsTeam2 { get; set; }


        [ColumnName("GoalDifference"), LoadColumn(8)]
        public float GoalDifference { get; set; }


        [ColumnName("Result"), LoadColumn(9)]
        public float Result { get; set; }


    }
}
