// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace MLNetTableSoccerML.Model.GoalDifference
{
    public class ModelOutput
    {
        public float Score { get; set; }
    }
}
